default: &default
  adapter: mysql2
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("DATABASE_USERNAME") { 'root' } %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  encoding: utf8mb4
  collation: utf8mb4_unicode_ci
  host: <%= ENV.fetch("DATABASE_HOST") { '127.0.0.1' } %>
  socket: /var/run/mysqld/mysqld.sock
  redis: &redis
    host: <%= ENV['APP_REDIS_HOST'] || "localhost" %>
    port: <%= ENV['APP_REDIS_PORT'] || "6379" %>
    db: 0
    options:
      namespace: rails_handle_exception

development:
  <<: *default
  database: rails_handle_exception_development

test:
  <<: *default
  database: rails_handle_exception_test

production:
  <<: *default
  database: rails_handle_exception_production
  password: <%= ENV['DATABASE_PASSWORD'] %>
